# Generated by Django 5.0.6 on 2024-07-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
